### ISSUE TITLE
ORCID DOI claims with certain resourceTypes remain in "waiting" state and do not appear in ORCID account

### ISSUE THREAD

**Issue by codycooperross** [datacite/volpino#108]
### Describe the bug

Some manual ORCID DOI claims remain in a "waiting" state indefinitely and receive errors like the following: 

`[Error] 0000-0002-4684-9769 – 10.4126/38m-002645284: [{"status"=>400, "title"=>{"response_code"=>"400", "developer_message"=>"400 Bad request: invalid value 'dissertation' for enum 'org.orcid.jaxb.model.common.WorkType'", "user_message"=>"Invalid value for type. ", "error_code"=>"9051", "more_info"=>"https://members.orcid.org/api/resources/troubleshooting"}}]`

The claimed DOIs do not appear in ORCID accounts. 

#### Expected Behaviour

The claim should be processed appropriately and transition from "waiting" to "done". 

#### Steps to Reproduce

Attempt to claim a DOI like the following using the "Claim DOI" button: https://commons.datacite.org/doi.org/10.13140/rg.2.1.2522.5849
https://commons.datacite.org/doi.org/10.4126/38m-38m-000000463

### Context (Environment)

The issue affects manual ORCID claiming in Commons. 

#### Hypothesis

This issue seems to only affect DOIs with a specific resourceType, specifically those listed here in the orcid_client gem here:

https://github.com/datacite/orcid_client/blob/9d5237e3e4369c0decf440bbe11575c73ae0bde3/lib/orcid_client/work_type.rb#L42

This is likely because the assigned ORCID work type, "dissertation", does not exist in the ORCID data model. Rather, the model includes work type "dissertation-thesis": 

https://github.com/ORCID/orcid-model/blob/a612165fee82fdbf930a381fb09b8f30e14340f6/src/main/java/org/orcid/jaxb/model/common/WorkType.java#L18

#### Possible Implementation

Changing the assigned work type in orcid_client from "dissertation" to "dissertation-thesis" may resolve this issue. The orcid_client work_type.rb code is also mirrored in the Typeable concern in volpino, but it's unclear if changing the code here would be significant: 

https://github.com/datacite/volpino/blob/d325a404586efa1d1529af9549652301292fe309/app/models/concerns/typeable.rb#L20

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2wg45)

**Comment by kjgarza** [comment]
oops, I think this was kind of left behind. check this out: https://github.com/datacite/volpino/issues/99

I think I forgot to merge that PR https://github.com/datacite/volpino/pull/100

**Comment by codycooperross** [comment]
> another user has reported a similar issue. some dois have conference paper resourceTypeGeneral https://profiles.datacite.org/admin/claims?user_id=0000-0002-0036-319x

This was a separate issue that has now been resolved #115
