### ISSUE TITLE
Tech Debt Week Q3

### ISSUE THREAD

**Issue by digitaldogsbody** [datacite/volpino#111]
Issues for Tech Debt week starting 15th Aug 2022

**Comment by digitaldogsbody** [comment]
Opened in the wrong repo (thanks Zenhub) :roll_eyes:

**Comment by sarala** [comment]
Do we have a new epic for this @digitaldogsbody?

**Comment by digitaldogsbody** [comment]
Yes: https://github.com/datacite/datacite/issues/1531
