### ISSUE TITLE
DOIs with ORCID not appearing in ORCID Record

### ISSUE THREAD

**Issue by kjgarza** [datacite/volpino#46]
Users is not receiving notification that DataCite is trying to modify his ORCID record

/Users/Kristian/Downloads/2017-05-23.tsv::          plain text::   TEXT
   52.30.225.208   User    Info    ecs-orcid-update-test-5-orcid-update-test-e6e5e5a0acc585f97700  Create DOI 10.17863/CAM.9809 for ORCID ID 0000-0003-4084-3363 pushed to Profiles service.              │
   52.30.225.208   User    Info    ecs-orcid-update-7-orcid-update-eeb9d7b8dee5a494a801    Create DOI 10.17863/CAM.9809 for ORCID ID 0000-0003-4084-3363 pushed to Profiles service.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1v3d)

**Comment by mfenner** [comment]
Tracked via datacite/datacite#331.
