### ISSUE TITLE
Logins are applied to the root domain

### ISSUE THREAD

**Issue by richardhallett** [datacite/volpino#57]
The profiles service applies it's authentication cookies to the "all" domain the tld, this is fine for most situations however if you have a separate auth system on the same domain, the cookie will apply in potentially a domain that you don't want it to.

This is specifically an issue for profiles.test.datacite.org and profiles.datacite.org where the JWT auth cookie is set for the datacite.org and therefore I believe the case is then any applications using the auth token (fabrica) will get the wrong session information.

**Comment by mfenner** [comment]
Can you elaborate? Using the jwt for `.datacite.org` instead of `.test.datacite.org`?

I will explore a more standard auth solution for DOI Fabrica: https://github.com/simplabs/ember-simple-auth

**Comment by richardhallett** [comment]
Yes I believe fabrica is picking up the same JWT cookie for both as the domain is just set to .datacite.org
I raised the issue here as although it manifests itself in Fabrica, I believe it's actually just to do with the domain of the JWT cookie which is set in volpino.

If you want to reproduce the problem, login to profiles.test.datacite.org then go to live fabrica, it will have logged you in but with the wrong user details.

**Comment by mfenner** [comment]
We could add a check that the JWT is from the correct place (using `iss`), but I want to move to a more standard approach anyway.
